In [294]:
# Use joblib file (dump and load)

import pandas as pd
from sklearn import tree
#from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import joblib

goal_data = pd.read_csv("stats.csv")
x = goal_data.drop(columns=["goals"])
y = goal_data["goals"]

model = DecisionTreeClassifier()
#model.fit(x,y)

#joblib.dump(model,"stats.joblib")
model = joblib.load("stats.joblib")


predictions = model.predict([[71,21,7]])
predictions

C:\Users\emirh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([2], dtype=int64)

In [295]:
# Accuracy score with train_test

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

model.fit(x_train,y_train)
predictions = model.predict(x_test)

score = accuracy_score(y_test,predictions)
score

0.0

In [298]:
goal_data = pd.read_csv("stats.csv")
x = goal_data.drop(columns=["goals"])
y = goal_data["goals"]

model = DecisionTreeClassifier()
model.fit(x,y)

tree.export_graphviz(model, out_file="stats.dot",
                    feature_names=["possesion", "shoots", "shoots_on_goal"],
                    class_names=sorted(y.unique()),
                    label="all",
                    rounded=True,
                    filled=True)

In [297]:
goal_data

    possesion  shoots  shoots_on_goal  goals
0          71      21               7    two
1          29       5               0   zero
2          67      30              12  three
3          33       5               5    two
4          65       8               2   zero
5          35      10               6  three
6          43       9               2    one
7          57      11               2    one
8          53      13               7   five
9          47      12               6    one
10         46      18               7    two
11         54       6               1   zero
12         46      15               2    one
13         54      14               3   zero
14         52      22              10   zero
15         48       8               3    one
16         38      20               9    one
17         62      25               5    one